### ISSUE TITLE
tulip

### ISSUE THREAD

**Issue by malaterre** [bzg/logiciel-libre-esr#17]
* http://tulip.labri.fr/TulipDrupal/

**Comment by bzg** [comment]
Merci pour toutes ces contributions - est-ce que tu peux les faire dans une PR ?

**Comment by malaterre** [comment]
J'ai fais le tour de ce que j'avais en tête (il m'en manque un de univ bordeaux mais j'ai une mémoire de poisson rouge), donc j'arréte la.

**Comment by bzg** [comment]
Ok, merci déjà pour tous ces éléments, c'est top !
