### ISSUE TITLE
Contributions OwnCloud de la DSI du CNRS

### ISSUE THREAD

**Issue by mherrb** [bzg/logiciel-libre-esr#20]
sur github: https://github.com/CNRS-DSI-Dev/

**Comment by bzg** [comment]
Merci - je l'ai ajouté la liste des "labo", mais je n'ai pas listé les logiciels.

J'ai aussi ajouté ce compte d'organisation [ici](https://github.com/DISIC/politique-de-contribution-open-source/commit/730004f97e9777170d3c66087e08f8f80795ab45).
