### ISSUE TITLE
Givaro / FFLAS-FFPACK / Linbox

### ISSUE THREAD

**Issue by P1K** [bzg/logiciel-libre-esr#57]
https://github.com/linbox-team

Contributeurs issus entre autres de :
http://univ-grenoble-alpes.fr/
https://www.umontpellier.fr/

**Comment by bzg** [comment]
Merci !

Je l'ai aussi ajouté [dans ce dépôt](https://github.com/DISIC/politique-de-contribution-open-source/commit/ec6db527f13e6793c2244ee587785355555e2ef2).
